### PR TITLE
Some code cleanup + add maven + protect against sql injection

### PR DESCRIPTION
**Pull request by larochef**
I did the following:
- Correct the different warnings that my IDE was telling me
- Add some protection against sql injections, using prepared statements instead of statements
- Add a pom.xml to help people come on the project

This PR refers to #1

### CODE REVIEW

**Comment by chashmeetsingh** [comment]
@larochef not sure whether this runs successfully as I no longer support this myself but inputs are welcome. If u say it works fine will merge it. Though I would first require you to squash your commits to 1 
Thanks !

**Comment by larochef** [comment]
If this project isn't used anymore, I don't really see the point spending more time on it ;) You should then remove the hacktoberfest tag from issues then.

**Comment by chashmeetsingh** [comment]
@larochef will have someone look at the code before I can merge this :)

**Comment by chashmeetsingh** [comment]
@larochef you mind deploying it on heroku? with some test data? will add you as a contributor if ...?

**Comment by larochef** [comment]
@chashmeetsingh Sorry for this late answer. I  don't have really know where this app is used and what are the plans for it, so I don't know who would benefit in it, and why contribute more.

**Pull request merged**
